### ISSUE TITLE
where is the folder 'images' ?

### ISSUE THREAD

**Issue by Willem-V** [freddyhard/galaxian#1]

**Comment by freddyhard** [comment]
i added both the graphics and sounds to their folders.
EDIT:
i also uploaded all those files again. i cannot remember that the original uploaded files had extra game play added - synchronized diving and leader Galaxians escaping onto the next level.

**Comment by Willem-V** [comment]
Thank you very much, I can see the files! Nice code btw :)

**Comment by freddyhard** [comment]
i have never wrote much in Python, but i was forced to write this. So i have no idea if this is correct use of Python even though it seems to work.
